# Generated by Django 5.2.5 on 2025-09-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_remove_order_products_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='emoji',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img/R.jpg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
